Comment out volunteers
asseth/EthCC-new-website pull request #16
Opened 2021-06-19 10:37 UTC by pscott

2021-06-19 10:40 UTC, pscott commented on src/pages/Tickets.tsx
> +  // VOLUNTEER_APPLICATION,
Commented out those because they weren't used anymore

2021-06-19 10:48 UTC, GuillaumeRx commented
I would prefer greying it ous as we did for the others :)

2021-06-19 10:48 UTC, GuillaumeRx commented on src/pages/Tickets.tsx
> +  // VOLUNTEER_APPLICATION,
You can delete them if they are not used

2021-06-21 07:05 UTC, GuillaumeRx requested changes
Requested changes in the other comment :)

2021-06-21 12:24 UTC, pscott commented
@GuillaumeRx For some reason I missed out the notification two days ago.. my bad. We need to merge this one ASAP (once it's good on your end), as people keep on submitting volunteer applications heheh

2021-06-21 12:33 UTC, GuillaumeRx requested changes

2021-06-21 12:33 UTC, GuillaumeRx commented on src/pages/Tickets.tsx
> +            {/* <Text
Please use the same method as the other disabled buttons for this one

2021-06-21 12:37 UTC, GuillaumeRx approved these changes
After discussion we're keeping the `NEED TO BUY DAI` commented; lgtm

2021-06-21 12:37 UTC, merged